import type { TranslationKey } from "@/lib/i18n";

export type BlogContentBlock =
  | { type: "h2" | "h3" | "p"; textKey: TranslationKey }
  | { type: "image"; src: string; altKey: TranslationKey };

export type BlogPost = {
  slug: string;
  titleKey: TranslationKey;
  excerptKey: TranslationKey;
  dateKey: TranslationKey;
  categoryKey: TranslationKey;
  readTime: number;
  color: string;
  coverLabel: string;
  /** Cover image path under /public — used for hero + Open Graph */
  coverImage: string;
  coverImageAltKey: TranslationKey;
  content: readonly BlogContentBlock[];
  relatedSlugs: readonly string[];
};

const whatIsGeoContent: readonly BlogContentBlock[] = [
  { type: "h2", textKey: "blog.post.geo.h2_1" },
  { type: "p", textKey: "blog.post.geo.p_1" },
  { type: "image", src: "/blog/what-is-geo.svg", altKey: "blog.post.geo.imageAlt" },
  { type: "h2", textKey: "blog.post.geo.h2_2" },
  { type: "p", textKey: "blog.post.geo.p_2" },
  { type: "h2", textKey: "blog.post.geo.h2_3" },
  { type: "h3", textKey: "blog.post.geo.h3_1" },
  { type: "p", textKey: "blog.post.geo.p_3" },
  { type: "h3", textKey: "blog.post.geo.h3_2" },
  { type: "p", textKey: "blog.post.geo.p_4" },
  { type: "h3", textKey: "blog.post.geo.h3_3" },
  { type: "p", textKey: "blog.post.geo.p_5" },
  { type: "h2", textKey: "blog.post.geo.h2_4" },
  { type: "p", textKey: "blog.post.geo.p_8" },
];

export const BLOG_POSTS: readonly BlogPost[] = [
  {
    slug: "what-is-geo",
    titleKey: "blog.post1.title",
    excerptKey: "blog.post1.excerpt",
    dateKey: "blog.post1.date",
    categoryKey: "blog.post1.category",
    readTime: 7,
    color: "#FF6600",
    coverLabel: "GEO",
    coverImage: "/blog/what-is-geo.svg",
    coverImageAltKey: "blog.post.geo.imageAlt",
    content: whatIsGeoContent,
    relatedSlugs: ["geo-vs-seo", "optimize-store-for-chatgpt", "ai-visibility-ecommerce-guide"],
  },
  {
    slug: "geo-vs-seo",
    titleKey: "blog.post2.title",
    excerptKey: "blog.post2.excerpt",
    dateKey: "blog.post2.date",
    categoryKey: "blog.post2.category",
    readTime: 8,
    color: "#ff983f",
    coverLabel: "GEO",
    coverImage: "/blog/geo-vs-seo.svg",
    coverImageAltKey: "blog.body.geoVsSeo.imageAlt",
    content: [
      { type: "h2", textKey: "blog.body.geoVsSeo.h2_1" },
      { type: "p", textKey: "blog.body.geoVsSeo.p_1" },
      { type: "image", src: "/blog/geo-vs-seo.svg", altKey: "blog.body.geoVsSeo.imageAlt" },
      { type: "h2", textKey: "blog.body.geoVsSeo.h2_2" },
      { type: "p", textKey: "blog.body.geoVsSeo.p_2" },
      { type: "h3", textKey: "blog.body.geoVsSeo.h3_1" },
      { type: "p", textKey: "blog.body.geoVsSeo.p_3" },
      { type: "h3", textKey: "blog.body.geoVsSeo.h3_2" },
      { type: "p", textKey: "blog.body.geoVsSeo.p_4" },
      { type: "h2", textKey: "blog.body.geoVsSeo.h2_3" },
      { type: "p", textKey: "blog.body.geoVsSeo.p_5" },
    ],
    relatedSlugs: ["what-is-geo", "product-page-seo-checklist", "ai-visibility-ecommerce-guide"],
  },
  {
    slug: "optimize-store-for-chatgpt",
    titleKey: "blog.post3.title",
    excerptKey: "blog.post3.excerpt",
    dateKey: "blog.post3.date",
    categoryKey: "blog.post3.category",
    readTime: 6,
    color: "#cc5200",
    coverLabel: "AI",
    coverImage: "/blog/optimize-store-for-chatgpt.svg",
    coverImageAltKey: "blog.body.chatgpt.imageAlt",
    content: [
      { type: "h2", textKey: "blog.body.chatgpt.h2_1" },
      { type: "p", textKey: "blog.body.chatgpt.p_1" },
      { type: "image", src: "/blog/optimize-store-for-chatgpt.svg", altKey: "blog.body.chatgpt.imageAlt" },
      { type: "h2", textKey: "blog.body.chatgpt.h2_2" },
      { type: "p", textKey: "blog.body.chatgpt.p_2" },
      { type: "h3", textKey: "blog.body.chatgpt.h3_1" },
      { type: "p", textKey: "blog.body.chatgpt.p_3" },
      { type: "h3", textKey: "blog.body.chatgpt.h3_2" },
      { type: "p", textKey: "blog.body.chatgpt.p_4" },
      { type: "h2", textKey: "blog.body.chatgpt.h2_3" },
      { type: "p", textKey: "blog.body.chatgpt.p_5" },
    ],
    relatedSlugs: ["what-is-geo", "ai-improve-product-descriptions", "ai-visibility-ecommerce-guide"],
  },
  {
    slug: "product-page-seo-checklist",
    titleKey: "blog.post4.title",
    excerptKey: "blog.post4.excerpt",
    dateKey: "blog.post4.date",
    categoryKey: "blog.post4.category",
    readTime: 9,
    color: "#929292",
    coverLabel: "SEO",
    coverImage: "/blog/product-page-seo-checklist.svg",
    coverImageAltKey: "blog.body.checklist.imageAlt",
    content: [
      { type: "h2", textKey: "blog.body.checklist.h2_1" },
      { type: "p", textKey: "blog.body.checklist.p_1" },
      { type: "image", src: "/blog/product-page-seo-checklist.svg", altKey: "blog.body.checklist.imageAlt" },
      { type: "h2", textKey: "blog.body.checklist.h2_2" },
      { type: "p", textKey: "blog.body.checklist.p_2" },
      { type: "h3", textKey: "blog.body.checklist.h3_1" },
      { type: "p", textKey: "blog.body.checklist.p_3" },
      { type: "h3", textKey: "blog.body.checklist.h3_2" },
      { type: "p", textKey: "blog.body.checklist.p_4" },
      { type: "h2", textKey: "blog.body.checklist.h2_3" },
      { type: "p", textKey: "blog.body.checklist.p_5" },
    ],
    relatedSlugs: ["shopify-seo-guide", "geo-vs-seo", "woocommerce-seo-guide"],
  },
  {
    slug: "shopify-seo-guide",
    titleKey: "blog.post5.title",
    excerptKey: "blog.post5.excerpt",
    dateKey: "blog.post5.date",
    categoryKey: "blog.post5.category",
    readTime: 10,
    color: "#FF6600",
    coverLabel: "SEO",
    coverImage: "/blog/shopify-seo-guide.svg",
    coverImageAltKey: "blog.body.shopify.imageAlt",
    content: [
      { type: "h2", textKey: "blog.body.shopify.h2_1" },
      { type: "p", textKey: "blog.body.shopify.p_1" },
      { type: "image", src: "/blog/shopify-seo-guide.svg", altKey: "blog.body.shopify.imageAlt" },
      { type: "h2", textKey: "blog.body.shopify.h2_2" },
      { type: "p", textKey: "blog.body.shopify.p_2" },
      { type: "h3", textKey: "blog.body.shopify.h3_1" },
      { type: "p", textKey: "blog.body.shopify.p_3" },
      { type: "h3", textKey: "blog.body.shopify.h3_2" },
      { type: "p", textKey: "blog.body.shopify.p_4" },
      { type: "h2", textKey: "blog.body.shopify.h2_3" },
      { type: "p", textKey: "blog.body.shopify.p_5" },
    ],
    relatedSlugs: ["product-page-seo-checklist", "woocommerce-seo-guide", "what-is-geo"],
  },
  {
    slug: "woocommerce-seo-guide",
    titleKey: "blog.post6.title",
    excerptKey: "blog.post6.excerpt",
    dateKey: "blog.post6.date",
    categoryKey: "blog.post6.category",
    readTime: 10,
    color: "#ff983f",
    coverLabel: "SEO",
    coverImage: "/blog/woocommerce-seo-guide.svg",
    coverImageAltKey: "blog.body.woocommerce.imageAlt",
    content: [
      { type: "h2", textKey: "blog.body.woocommerce.h2_1" },
      { type: "p", textKey: "blog.body.woocommerce.p_1" },
      { type: "image", src: "/blog/woocommerce-seo-guide.svg", altKey: "blog.body.woocommerce.imageAlt" },
      { type: "h2", textKey: "blog.body.woocommerce.h2_2" },
      { type: "p", textKey: "blog.body.woocommerce.p_2" },
      { type: "h3", textKey: "blog.body.woocommerce.h3_1" },
      { type: "p", textKey: "blog.body.woocommerce.p_3" },
      { type: "h3", textKey: "blog.body.woocommerce.h3_2" },
      { type: "p", textKey: "blog.body.woocommerce.p_4" },
      { type: "h2", textKey: "blog.body.woocommerce.h2_3" },
      { type: "p", textKey: "blog.body.woocommerce.p_5" },
    ],
    relatedSlugs: ["shopify-seo-guide", "product-page-seo-checklist", "salla-seo-guide"],
  },
  {
    slug: "salla-seo-guide",
    titleKey: "blog.post7.title",
    excerptKey: "blog.post7.excerpt",
    dateKey: "blog.post7.date",
    categoryKey: "blog.post7.category",
    readTime: 8,
    color: "#cc5200",
    coverLabel: "SEO",
    coverImage: "/blog/salla-seo-guide.svg",
    coverImageAltKey: "blog.body.salla.imageAlt",
    content: [
      { type: "h2", textKey: "blog.body.salla.h2_1" },
      { type: "p", textKey: "blog.body.salla.p_1" },
      { type: "image", src: "/blog/salla-seo-guide.svg", altKey: "blog.body.salla.imageAlt" },
      { type: "h2", textKey: "blog.body.salla.h2_2" },
      { type: "p", textKey: "blog.body.salla.p_2" },
      { type: "h3", textKey: "blog.body.salla.h3_1" },
      { type: "p", textKey: "blog.body.salla.p_3" },
      { type: "h2", textKey: "blog.body.salla.h2_3" },
      { type: "p", textKey: "blog.body.salla.p_4" },
    ],
    relatedSlugs: ["zid-seo-guide", "product-page-seo-checklist", "what-is-geo"],
  },
  {
    slug: "zid-seo-guide",
    titleKey: "blog.post8.title",
    excerptKey: "blog.post8.excerpt",
    dateKey: "blog.post8.date",
    categoryKey: "blog.post8.category",
    readTime: 8,
    color: "#929292",
    coverLabel: "SEO",
    coverImage: "/blog/zid-seo-guide.svg",
    coverImageAltKey: "blog.body.zid.imageAlt",
    content: [
      { type: "h2", textKey: "blog.body.zid.h2_1" },
      { type: "p", textKey: "blog.body.zid.p_1" },
      { type: "image", src: "/blog/zid-seo-guide.svg", altKey: "blog.body.zid.imageAlt" },
      { type: "h2", textKey: "blog.body.zid.h2_2" },
      { type: "p", textKey: "blog.body.zid.p_2" },
      { type: "h3", textKey: "blog.body.zid.h3_1" },
      { type: "p", textKey: "blog.body.zid.p_3" },
      { type: "h2", textKey: "blog.body.zid.h2_3" },
      { type: "p", textKey: "blog.body.zid.p_4" },
    ],
    relatedSlugs: ["salla-seo-guide", "product-page-seo-checklist", "optimize-store-for-chatgpt"],
  },
  {
    slug: "ai-improve-product-descriptions",
    titleKey: "blog.post9.title",
    excerptKey: "blog.post9.excerpt",
    dateKey: "blog.post9.date",
    categoryKey: "blog.post9.category",
    readTime: 6,
    color: "#FF6600",
    coverLabel: "AI",
    coverImage: "/blog/ai-improve-product-descriptions.svg",
    coverImageAltKey: "blog.body.aiDesc.imageAlt",
    content: [
      { type: "h2", textKey: "blog.body.aiDesc.h2_1" },
      { type: "p", textKey: "blog.body.aiDesc.p_1" },
      { type: "image", src: "/blog/ai-improve-product-descriptions.svg", altKey: "blog.body.aiDesc.imageAlt" },
      { type: "h2", textKey: "blog.body.aiDesc.h2_2" },
      { type: "p", textKey: "blog.body.aiDesc.p_2" },
      { type: "h3", textKey: "blog.body.aiDesc.h3_1" },
      { type: "p", textKey: "blog.body.aiDesc.p_3" },
      { type: "h3", textKey: "blog.body.aiDesc.h3_2" },
      { type: "p", textKey: "blog.body.aiDesc.p_4" },
      { type: "h2", textKey: "blog.body.aiDesc.h2_3" },
      { type: "p", textKey: "blog.body.aiDesc.p_5" },
    ],
    relatedSlugs: ["optimize-store-for-chatgpt", "product-page-seo-checklist", "what-is-geo"],
  },
  {
    slug: "ai-visibility-ecommerce-guide",
    titleKey: "blog.post10.title",
    excerptKey: "blog.post10.excerpt",
    dateKey: "blog.post10.date",
    categoryKey: "blog.post10.category",
    readTime: 9,
    color: "#ff983f",
    coverLabel: "GEO",
    coverImage: "/blog/ai-visibility-ecommerce-guide.svg",
    coverImageAltKey: "blog.body.aiVisibility.imageAlt",
    content: [
      { type: "h2", textKey: "blog.body.aiVisibility.h2_1" },
      { type: "p", textKey: "blog.body.aiVisibility.p_1" },
      { type: "image", src: "/blog/ai-visibility-ecommerce-guide.svg", altKey: "blog.body.aiVisibility.imageAlt" },
      { type: "h2", textKey: "blog.body.aiVisibility.h2_2" },
      { type: "p", textKey: "blog.body.aiVisibility.p_2" },
      { type: "h3", textKey: "blog.body.aiVisibility.h3_1" },
      { type: "p", textKey: "blog.body.aiVisibility.p_3" },
      { type: "h3", textKey: "blog.body.aiVisibility.h3_2" },
      { type: "p", textKey: "blog.body.aiVisibility.p_4" },
      { type: "h2", textKey: "blog.body.aiVisibility.h2_3" },
      { type: "p", textKey: "blog.body.aiVisibility.p_5" },
    ],
    relatedSlugs: ["what-is-geo", "geo-vs-seo", "optimize-store-for-chatgpt"],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}

export function getRelatedPosts(post: BlogPost): BlogPost[] {
  return post.relatedSlugs
    .map((s) => getBlogPost(s))
    .filter((p): p is BlogPost => !!p);
}
